### ISSUE TITLE
Showermax has too thick aluminum lightguide

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/remoll-showermax-generator#3]
You can see the lines in the part of the lightguide that is closest to the PMT. This is not affected by changing the 3.302 to something smaller. With this thickness of aluminum, it probably generates a lot of secondaries.
![image](https://user-images.githubusercontent.com/4656391/111815160-57462f00-88a9-11eb-90ed-ad6e21b8b990.png)

**Comment by wdconinc** [comment]
@Gorgannejad

**Comment by wdconinc** [comment]
@rahmans1 I think this may be what Dustin was referring yesterday. Elham will be looking into fixing this.

**Comment by wdconinc** [comment]
@Gorgannejad Just looking at this briefly on my phone. Line 129 in showermaxgen.py should have x1 set to thick_mirror_box_bot instead of ..._tungstenquartz, I think.

**Comment by wdconinc** [comment]
Also, aluminum thickness should be 20 mil thick, or 0.5 mm, per email from Dustin.

**Comment by wdconinc** [comment]
@Gorgannejad Was this aluminum lightguide thickness issue ever fixed in the version here on GitHub? If so, we can close this issue.

**Comment by mcnudust** [comment]
Hi all,

I believe this issue was fixed a couple months ago.  Others can chime-in 
here if needed.

Cheers,
Dustin
